export const HANDOFF_REASON = {
  HUMAN_REQUESTED: 'HUMAN_REQUESTED',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',
  COMPLEX_REQUEST: 'COMPLEX_REQUEST',
  ESCALATION: 'ESCALATION',
  PAYMENT_ISSUE: 'PAYMENT_ISSUE',
  TECHNICAL_ISSUE: 'TECHNICAL_ISSUE',
  COMPLAINT: 'COMPLAINT',
  OTHER: 'OTHER',
} as const;

export type HandoffReason =
  (typeof HANDOFF_REASON)[keyof typeof HANDOFF_REASON];

export const HANDOFF_REASON_VALUES: HandoffReason[] = Object.values(
  HANDOFF_REASON,
);